### ISSUE TITLE
Add method which calculates difference between two curves

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/beprof#21]
Two profiles might have different domain (set of X coordinates).
We want to calculate difference of these two curves, i.e. by calling

```
c1 = Curve(...)
c2 = Curve(...)
cdiff = c1.subtract(c2) 
```

Domains of c1 and c2 might be overlapping, disjoint, equal or have whatever arrangment.

**Comment by matkrak** [comment]
Having rebinned methods alredy implemented makes it easier. Still requires efficient code and some testing. Writing the first version should take more then 1 hour, but I am pretty sure its not going to be the final version, so lets say 2 hours for this method.

**Comment by matkrak** [comment]
1) If the domains of c1 and c2 are the same, this is the easiest example subtract() should return a new curve that is difference of these 2 given
2) If both domains are in the same section [a, b] but have different points - this is also not a problem since we have rebinning methods. I think if we call `c1.subtract(c2)` then c2 should be rebinned to c1 domain and then subtraction should be done. Correct me if I am wrong.
3) If one of the domains includes the other, i.e. c1 domain is 'inside' c2 domain, then probably we want do the subtraction with all the values from outside the narrow domain = 0 ? or nan maybe but 0 seems more natural.
4) If the domains are disjoint, what should be done? It should either throw exception (I am not sure if this behavior is desired) or 'append' data to one of curves i.e. new domain points are these from the opposite domain, and the value for each is 0 (or nan) and then we have situation as in 3)

**Comment by grzanka** [comment]
First, take look at an example of `np.subtract` function. See how does it deal with subtractring of subclasses of np.array. It is described in http://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html (Output type determination).

Let us discuss two scenarios:
A) `c3 = subtract(c1,c2)` - function at the level of module
B) `c3 = c1.subtract(c2)` - method in Curve class

Keep in mind that c1 and c2 might also be instances of some Curve subclasses, i.e. Profile and might have some metadata attached.

The questions are:
1.  which should be the type of c3 if c1 and c2 are some (possible different) subclasses of Curve ?
2.  which metadata will go to c3 (assume that c1.metadata['range'] is 2 and c2.metadata['range'] is 3. What should go to c3.metadata['range'] ?)
What do you think ?

It should be clearly seen by the user whether new object is created or not. I would assume that by default we always create new object.  If user tells us we should avoid creating new object then:
- in case we can subtract without creating new object we do it (i.e. the same domains)
- in case we need to create new object, we raise an exception.

Ad1. Scenario A) - yes, new object. Scenario B) - it depends whether user wants new object or not.

Ad2. c2 should not be modified. Imagine following code:

```
x = 5
y = 1
z = x - y
```

After execution of these 3 lines y should be still equal to 1. In cannot be modified during subtraction.

Ad3. It should be up to the user. You could add a parameter and set it by default to zero. See for example:
http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.ndimage.interpolation.shift.html
- cval parameter.

Ad4. Your solution looks OK, but you should also let user decide whether to limit the subtraction to c1 domain or to extend it. I would say that your version should be the default.

What about new estimated time of this task ?

**Comment by matkrak** [comment]
Ok, thanks, you made it pretty clear. If there are any questions I will pose them here.
And yes new estimated time is much more then 2 hours. 
In fact I hoped to close this issue and the 2 already opened PR today, but seems like this one is gonna take a lot of time. Still possible to close it today after all!

**Comment by grzanka** [comment]
Solved here https://github.com/grzanka/beprof/pull/26
